### ISSUE TITLE
Glance type watch setting doesn't work

### ISSUE THREAD

**Issue by koreyhinton** [Lisapple/Closer#5]
In app settings in the Apple watch app, the _Show as Glance_ setting isn't working when I select _Closest Countdown to Finish_ it just always shows the last selected page instead in the glance/complication. I wonder if this is because of app groups working differently in watchOS >= 2. People have claimed that app settings can sync properly using the watch settings bundle if setup properly but I haven't been able to get it to work myself.

**Comment by Lisapple** [comment]
Yes, you're right, thank you to point it out. I changed the app name from 'WatchKit App' to 'Watch App' on day and I think it messed with the app groups.
There was also an error on glance and complication code, where the user defaults used were from app score, not settings scope, so settings were of course not taken in consideration (and always set on last selected page setting).
This is fixed on commit a63dc3.
